### ISSUE TITLE
The eclipse dependencies for spring boot are incorrect.

### ISSUE THREAD

**Issue by cimela** [cimela/e-restaurant#2]
In branch **eR-UI-Main**, the dependencies for **appserver** is correct.
In branch **eR-D-0001-Model**, the dependencies for **appserver** and **model** are only the basic one

Execute **mvn eclipse:eclipse** in **erestaurant** to generate eclipse configure

**Comment by longkid** [comment]
Fixed at commit commit 76caa171fa860710db0ab0518a3fbb0a8272f5a4 
Author: Lam Ho <hotienlam@gmail.com>
Date:   Sat Aug 25 20:55:28 2018 +0700

    [Project]
    Issue: The eclipse dependencies for spring boot are incorrect.
    Root cause: Maven failed to grab dependencies for model project
    Solution: Refer to https://stackoverflow.com/questions/46984069/why-is-spring-boot-dependencies-in-dependencymanagement
